Added missing parameters required to run program on the sample data
fluxnet/ONEFlux pull request #58
Opened 2024-07-29 18:27 UTC by isaacaka

Added missing parameters (first and last years for the ERA product) required to run program on the US-ARc sample data

2024-08-08 13:53 UTC, dorchard commented
Closes https://github.com/Cambridge-ICCS/ONEFlux/issues/13

2024-09-11 15:49 UTC, dorchard requested changes

2024-09-11 15:49 UTC, dorchard commented on README.md
> +python runoneflux.py partition_nt "../datadir/" US-ARc "US-ARc_sample_input" 2005 2006 -l fluxnet_pipeline_US-ARc.log --era-fy 1989 --era-ly 2014
--era-fy and --era-ly not needed here.

2024-09-11 15:49 UTC, dorchard commented on README.md
> +python runoneflux.py partition_dt "../datadir/" US-ARc "US-ARc_sample_input" 2005 2006 -l fluxnet_pipeline_US-ARc.log --prod y --perc 50 --force-py --era-fy 1989 --era-ly 2014
--era-fy and --era-ly not needed here.

2024-09-11 15:49 UTC, dorchard commented on README.md
> +- https://github.com/fluxnet/ONEFlux/issues/39
```suggestion
```

2024-09-11 15:49 UTC, dorchard commented on README.md
> +Issues Related to Running Sample US-ARc
```suggestion
```

2024-09-11 16:10 UTC, isaacaka commented on README.md
> +python runoneflux.py partition_nt "../datadir/" US-ARc "US-ARc_sample_input" 2005 2006 -l fluxnet_pipeline_US-ARc.log --era-fy 1989 --era-ly 2014
```suggestion
python runoneflux.py partition_nt "../datadir/" US-ARc "US-ARc_sample_input" 2005 2006 -l fluxnet_pipeline_US-ARc.log
```

2024-09-11 16:10 UTC, isaacaka commented on README.md
> +python runoneflux.py partition_dt "../datadir/" US-ARc "US-ARc_sample_input" 2005 2006 -l fluxnet_pipeline_US-ARc.log --prod y --perc 50 --force-py --era-fy 1989 --era-ly 2014
```suggestion
python runoneflux.py partition_dt "../datadir/" US-ARc "US-ARc_sample_input" 2005 2006 -l fluxnet_pipeline_US-ARc.log --prod y --perc 50 --force-py
```

2024-09-11 16:14 UTC, dorchard approved these changes
Looks good to me if @gilbertozp is happy with this.

2024-09-30 15:01 UTC, gilbertozp approved these changes
Added parameters and documentation look good

2024-09-30 15:01 UTC, merged